name: streaming_clusters
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - hdbscan
  - tqdm
  - pip
  - pip:
      - river
      - plotly
      - pytest
      - loguru
      - python-dotenv
      - ruff
      - fastapi
      - uvicorn
      - pyaml_env
